name: sicp ci

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: [ '7.7' ]
    name: Racket ${{ matrix.racket-version }}
    steps:
      - uses: actions/checkout@master
      - name: Setup Racket
        uses: Bogdanp/setup-racket@v0.8
        with:
          architecture: x64
          version: ${{ matrix.racket-version }}
      - run: test ./src/**/*-test.rkt
